deployment:
    port: 5000
metrics:
    metricsDefinition:
    - name: "inicio_solicitud_presupuesto"
      type: Counter
      info: 
        name: "incio_solicitud_presupuesto"
        help: "Total clicks to 'Iniciar presupuesto' button"
    - name: "fin_solicitud_presupuesto"
      type: Counter
      info: 
        name: "fin_solicitud_presupuesto"
        help: "Total clicks to 'Finalizar presupuesto' button"
    - name: "abrir_parada_google_maps"
      type: Counter
      labelNames: ["linea"]
      info: 
        name: "abrir_parada_google_maps"
        help: "Total clicks to 'google Maps' button "
    - name: "descargar_horario"
      type: Counter
      labelNames: ["linea"]
      info: 
        name: "descargar_horario"
        help: "Total clicks to 'Ver Horario' button "
    - name: "revisar_info_tarjetas"
      type: Counter
      labelNames: ["tipo_tarjeta"]
      info: 
        name: "revisar_info_tarjetas"
        help: "Total clicks to 'recarga tarjetas tab' '"
    - name: "consultar_loc_puntos_recarga"
      type: Counter
      labelNames: ["punto_recarga"]
      info: 
        name: "consultar_loc_puntos_recarga"
        help: "Total clicks to 'ani chargin point location' '"
    - name: "test_gauge1"
      type: Gauge
      info: 
        name: "web_test_gauge2"
        help: "Total test gauge"
    - name: "test_summary"
      type: Summary
      percentiles: [0, 0.25, 0.50, 0.75, 0.99]
      info: 
        name: "web_test_summary"
        help: "Total test gauge"
    - name: "test_counter"
      type: Counter
      info: 
        name: "web_test_counter"
        help: "Total test counter"